version: '3.8'

services:
  # Load Balancer (Nginx)
  load-balancer:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app1
      - app2
    networks:
      - exploration-network
    restart: unless-stopped

  # Application Instance 1
  app1:
    build: .
    environment:
      - PORT=3000
      - SERVER_ID=server-1
      - NODE_ENV=production
    networks:
      - exploration-network
    restart: unless-stopped

  # Application Instance 2
  app2:
    build: .
    environment:
      - PORT=3000
      - SERVER_ID=server-2
      - NODE_ENV=production
    networks:
      - exploration-network
    restart: unless-stopped

  # Redis for analytics persistence
  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    networks:
      - exploration-network
    restart: unless-stopped

  # Analytics Database
  analytics-db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=analytics
      - POSTGRES_USER=analytics_user
      - POSTGRES_PASSWORD=secure_password_123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - exploration-network
    restart: unless-stopped

networks:
  exploration-network:
    driver: bridge

volumes:
  redis_data:
  postgres_data: